OpenScienceBundle\Entity\Mots:
    type: entity
    table: null
    repositoryClass: OpenScienceBundle\Repository\MotsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        langue:
            type: string
            length: '2'
        mots:
            type: string
            length: 255
            unique: true
        definition:
            type: text           
        niveau:
            type: integer
        link:
            type: integer
    lifecycleCallbacks: {  }
