open_science_homepage:
    path:     /
    defaults: { _controller: OpenScienceBundle:EndGame:index }

first:
    path:     /first
    defaults: { _controller: OpenScienceBundle:EndGame:first }

second:
    path:     /second
    defaults: { _controller: OpenScienceBundle:EndGame:second }

third:
    path:     /third
    defaults: { _controller: OpenScienceBundle:EndGame:third }
