<?php

namespace OpenScienceBundle\Repository;

/**
 * MotsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotsRepository extends \Doctrine\ORM\EntityRepository
{
}
